// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgvcbkfkshwitcpmhsun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBndmNia2Zrc2h3aXRjcG1oc3VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODI3MjksImV4cCI6MjA2NTU1ODcyOX0.MRVQpSjC0W4a1VJTJwoqilCOS1w0zjnD6tPhAguHG4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);